/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface OhblogMenu {
        "backColor": string;
        "imagem": string;
        "titulos": string;
        "urls": string;
    }
}
declare global {
    interface HTMLOhblogMenuElement extends Components.OhblogMenu, HTMLStencilElement {
    }
    var HTMLOhblogMenuElement: {
        prototype: HTMLOhblogMenuElement;
        new (): HTMLOhblogMenuElement;
    };
    interface HTMLElementTagNameMap {
        "ohblog-menu": HTMLOhblogMenuElement;
    }
}
declare namespace LocalJSX {
    interface OhblogMenu {
        "backColor"?: string;
        "imagem"?: string;
        "titulos"?: string;
        "urls"?: string;
    }
    interface IntrinsicElements {
        "ohblog-menu": OhblogMenu;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ohblog-menu": LocalJSX.OhblogMenu & JSXBase.HTMLAttributes<HTMLOhblogMenuElement>;
        }
    }
}
